
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ROQUE_GRANDE = 9;
  public static final int VITORIA_BRANCAS = 12;
  public static final int NUMERO_TURNO = 11;
  public static final int COLUNA = 3;
  public static final int EMPATE = 14;
  public static final int XEQUE = 6;
  public static final int PROMOCAO = 8;
  public static final int LINHA = 2;
  public static final int VITORIA_PRETAS = 13;
  public static final int EOF = 0;
  public static final int XEQUEMATE = 7;
  public static final int CAPTURA = 5;
  public static final int ROQUE_PEQUENO = 10;
  public static final int error = 1;
  public static final int PECA = 4;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LINHA",
  "COLUNA",
  "PECA",
  "CAPTURA",
  "XEQUE",
  "XEQUEMATE",
  "PROMOCAO",
  "ROQUE_GRANDE",
  "ROQUE_PEQUENO",
  "NUMERO_TURNO",
  "VITORIA_BRANCAS",
  "VITORIA_PRETAS",
  "EMPATE"
  };
}

